apiVersion: apps/v1
kind: Deployment
metadata:
  name: podname
  labels:
    app: podname
spec:
  replicas: 10
  selector:
    matchLabels:
      app: podname
  template:
    metadata:
      labels:
        app: podname
    spec:
      containers:
      - name: podname
        #image: registry.digitalocean.com/doks-docr/podname:v1
        image: dellabeneta/podname:v1
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #   limits:
        #     cpu: "200m"
        #     memory: "256Mi"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
