name: Build and Deploy
on:
  push:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:v${{ github.run_number }}

      - name: Update deployment file
        run: |
          sed -i "s|${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:.*|${{ env.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:v${{ github.run_number }}|" k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'dellabeneta'
          git config --global user.email 'm.dellabeneta@gmail.com'
          git add k8s/deployment.yaml
          git commit -m "Update image tag to v${{ github.run_number }}"
          git push
