name: Build and Deploy
on:
  push:
    paths:
      - 'app/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual workflow run'
        required: false
        default: 'Manual trigger'

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Generate Image Tag
        id: image_tag
        run: echo "tag=v${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ steps.image_tag.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update deployment file
        run: |
          sed -i "s|${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:.*|${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}|" k8s/deployment.yaml

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag to ${{ needs.build.outputs.image_tag }}
          file_pattern: k8s/deployment.yaml
